services:
  database:
    container_name: edu-web-database
    image: mariadb:latest
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_DATABASE: app_db
      MYSQL_ROOT_PASSWORD: studoo
      MYSQL_USER: stud
      MYSQL_PASSWORD: studoo
      # Si tu changes le mot de passe root ou stud, change aussi le mot de passe dans le fichier .env et dans la config du service dbgate
#      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      TZ: Europe/Paris
    volumes:
      - ./var/dbdata:/var/lib/mysql
  mailer:
    container_name: edu-web-mailer
    image: axllent/mailpit
    ports:
      - "1025"
      - "8025:8025"
    environment:
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
  dbgate:
    container_name: edu-web-dbgate
    image: dbgate/dbgate
    restart: always
    ports:
      - 8082:3000
    volumes:
      - ./var/dbgate:/root/.dbgate
      - ./var/logs:/home/jan
    environment:
      CONNECTIONS: con1,con2

      LABEL_con1: MySql
      SERVER_con1: database
      USER_con1: root
      PASSWORD_con1: studoo
      PORT_con1: 3306
      ENGINE_con1: mysql@dbgate-plugin-mysql

      LABEL_con2: SQLite
      FILE_con2: /home/jan/core_logs.sqlite
      ENGINE_con2: sqlite@dbgate-plugin-sqlite

  phpmyadmin:
    container_name: edu-web-pma
    image: phpmyadmin/phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_HOST: database
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
      UPLOAD_LIMIT: 1G
      MEMORY_LIMIT: 512M
      MAX_EXECUTION_TIME: 0
    restart: always
    links:
      - database
volumes:
  dbgate-data:
    driver: local